# Default values for Testrail.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Testrail server properties
srv:
  replicaCount: 1

  image:
    repository: testrail/apache
    tag: 7.5.3.1000
    pullPolicy: IfNotPresent

# If you don't want to specify resources, comment the following lines.
# It will increase chances chart run on environments with little
# resources, such as Minikube. But in production environments I recommend to use parameters set below.
  resources:
    requests:
      cpu: 200m
      memory: 600Mi
    limits:
      cpu: "1"
      memory: 1536Mi

  servicePort: 8000

  nodeSelector: {}
# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ldap:
    enable: false
    auth_host: ldap://example.com
    auth_port: 389
    auth_bind_dn: user@example.com
    auth_bind_password: password
    auth_dn: OU=Users,DC=example,DC=com
    auth_filter: (&(objectclass=user)(sAMAccountName=%name%))
    auth_fallback: true
    auth_create_account: false
    auth_name_attribute: displayname
    auth_mail_attribute: mail

  ad:
    enable: false
    auth_host: ldap://example.com
    auth_port: 389
    auth_dn: OU=Users,DC=example,DC=com
    auth_fallback: true
    auth_create_account: true
    auth_domain: EXAMPLE
    auth_membership: /^CN=My Group,/

db:
  replicaCount: 1

  image:
    repository: testrail/mysql
    tag: 6.3.1.1006
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 600Mi
    limits:
      cpu: "700m"
      memory: 1536Mi    

  nodeSelector: {}
# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/

# MySQL DB settings and credentials
  dbname: "testrail"
  mysql_user: "testrail"
  mysql_password: "password"
  root_password: "password"

cassandra:
  image:
    repository: testrail/cassandra
    tag: latest
# If you don't want to specify resources, comment the following lines.
# It will increase chances chart run on environments with little
# resources, such as Minikube. But in production environments I recommend to use parameters set below.
  resources:
    requests:
      cpu: 200m
      memory: 600Mi
    limits:
      cpu: "1"
      memory: 1536Mi

ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
  - name: testrail.organization.com

  annotations:
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # This property allows for reports up to a certain size to be uploaded to SonarQube
  # nginx.ingress.kubernetes.io/proxy-body-size: "8m"

  tls:
  # Secrets must be manually created in the namespace.
  - secretName: testrail-tls
    hosts:
      - testrail.organization.com
