apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testrail-network-policy
  labels:
    {{- include "testrail.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "testrail.selectorLabels" . | nindent 6 }}

  policyTypes:
  - Ingress
  ingress:
  - from:
      - ipBlock:
         cidr: "0.0.0.0/0"
    ports:
    - protocol: TCP
      port: 80
