apiVersion: v1
kind: Secret
metadata:
  name: {{ include "testrail.fullname" . }}
  labels:
    {{- include "testrail.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_DATABASE:      {{ .Values.db.dbname | b64enc | quote }}
  MYSQL_USER:          {{ .Values.db.mysql_user | b64enc | quote }}
  MYSQL_PASSWORD:      {{ .Values.db.mysql_password | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.db.root_password | b64enc | quote }}
