apiVersion: v1
kind: Service
metadata:
  name: {{ include "testrail.fullname" . }}
  labels:
    {{- include "testrail.labels" . | nindent 4 }}

spec:
  ports:
    - name: http
      port: {{ .Values.srv.servicePort }}
      targetPort: 80
  selector:
    {{- include "testrail.selectorLabels" . | nindent 4 }}
